### ISSUE TITLE
Error connecting nfc reader

### ISSUE THREAD

**Issue by User69-cmd** [skylandersNFC/Mifare-1K-Magic-UID-Reset#1]
If I use CMD i get this message: Error connecting nfc reader
If I use the exe i get this message: MSVCP100.dll & MSVCR100.dll are not found

Can u please try to fix this, because i really need the software

**Comment by skylandersNFC** [comment]
The "Error connecting nfc reader" error comes from the lack of **[ACR122U](https://skylandersnfc.github.io/Docs/Skylanders_Buying_List/Skylanders_NFC_Devices/ACR122U/)** reader connected or no drivers installed for it. You need to have all those already setup .

The "MSVCP100.dll & MSVCR100.dll" error comes from lack of **[Microsoft Visual C++ 2010 Service Pack 1 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=26999)**. You also need to have it installed to run the exe. 

Here is a video: **[How To Fix Error: "MSVCP100.dll & MSVCR100.dll is missing" ](https://www.youtube.com/watch?v=o8TqoZ67kMU)**

P.S. I've added **[Prerequisites](https://github.com/skylandersNFC/Mifare-1K-Magic-UID-Reset/tree/main?tab=readme-ov-file#prerequisites)** section on the main page.

And please report back when it's fixed, so i can close the issue. Gratitude.
